### ISSUE TITLE
Sales Kit - Benta

### ISSUE THREAD

**Issue by unclejo** [MIS-SEG-Android-Team/Guanzon-Sales-Kit#2]
### Product Inquiry

- [x] 1. **User Authentication:**
   - User logs in or creates an account if not registered.

- [x] 2. **Product Inquiry Page:**
   - User accesses the product inquiry page.
   - User selects the desired motorcycle brand from the available options.

- [x] 3. **Motorcycle Units Selection:**
   - Upon brand selection, the app displays all motorcycle units available for the selected brand.
   - User chooses a specific motorcycle unit for inquiry.

- [x] 4. **Inquiry Page:**
   - User is directed to the inquiry page for the selected motorcycle unit.
   - Inquiry page displays:
     - Image of the selected motorcycle unit.
     - Variant/Color selection options.
     - Payment method selection:
       - Cash payment.
       - Installment payment.
 
- [x] 5. **Financier Information Collection:**
   - After configuring payment options, user proceeds to collect financier information.
   - User provides:
     - Full name.
     - Address and contact details.
     - Country 
- [x] 6. **Customer Information Collection:**
   - After completing financier information, user proceeds to collect customer information.
   - User provides:
     - Full name.
     - Birth date and birthplace.
     - Address and contact details.
     - Relationship of customer to its financier
- [x] 7. **Saving Inquiry Entry:**
   - User saves the completed inquiry entry.

- [x] 8. **View Inquiry Status:**
   - User can access a separate page to view the status of mc model payment details.

**Comment by johncarlostacruz** [comment]
- [ ] 2. Product Inquiry Page:

>problem sending OTP cant create product inquiry

**Comment by ggutoman** [comment]
> 01\19\24
> 
> * [ ]  2. Product Inquiry Page:
> 
> > cant complete account entry info
> > problem sending OTP cant create product inquiry
> > Sending OTP to Number instead of email
> 
> 01\22\2024
> 
> * [x]  7. Saving Inquiry Entry:
> 
> > Cash Entry: lumalabas yung computation ng Installment.
> > Installment: hindi nag cacalculate.
> > Done Entry Inquiries: pag ibaback na bumabalik sya sa entry ng info ng client .
> 
> * [x]  8. View Inquiry Status:
> 
> > hindi nag save sa history.
> 
> 01\24\2024
> 
> * [x]  1. User Authentication:
> 
> > a. Mobile no - required paba ito?. -> yes hindi na required
> > b. pagkatapos mag submit info sa sign up bigla nalan mag coclose.
> > c. after maclick yung message na ''must complete account to access this feature may lumalabas na messager box "user profile not found".
> > c2. notification title "under development".
> > d. to complete account need paba ilagay ulit yung first name at last name ng user meron na kasi ito sa sign up form.
> > e. pagka submit ng info sa pag complete account ito lumalabas na message "unset parameter detected: message: sGCashNox".
> > e2. submit again yung info ito yung lumalabas na message "unique constraint failed: Client_Profile_Info.sUSerIDxx"

**Comment by ggutoman** [comment]
> > 01\19\24
> > 
> > * [ ]   2. Product Inquiry Page:
> > 
> > > cant complete account entry info
> > > problem sending OTP cant create product inquiry
> > > Sending OTP to Number instead of email
> > 
> > 
> > 01\22\2024
> > 
> > * [x]   7. Saving Inquiry Entry:
> > 
> > > Cash Entry: lumalabas yung computation ng Installment.
> > > Installment: hindi nag cacalculate.
> > > Done Entry Inquiries: pag ibaback na bumabalik sya sa entry ng info ng client .
> > 
> > 
> > 
> > * [x]   8. View Inquiry Status:
> > 
> > > hindi nag save sa history.
> > 
> > 
> > 01\24\2024
> > 
> > * [x]   1. User Authentication:
> > 
> > > a. Mobile no - required paba ito?.
> > > b. pagkatapos mag submit info sa sign up bigla nalan mag coclose.
> > > c. after maclick yung message na ''must complete account to access this feature may lumalabas na messager box "user profile not found".
> > > c2. notification title "under development".
> > > d. to complete account need paba ilagay ulit yung first name at last name ng user meron na kasi ito sa sign up form.
> > > e. pagka submit ng info sa pag complete account ito lumalabas na message "unset parameter detected: message: sGCashNox".
> > > e2. submit again yung info ito yung lumalabas na message "unique constraint failed: Client_Profile_Info.sUSerIDxx"

1. User Authentication:
  a. Yes, hindi na required
  b. Fixed
  c. Fixed
  c2. Fixed
  d. Yes, kailangan parin.
  e. Fixed
  e2. Fixed, eto yung dinelete na account ni mam she pero sa app_user_device table hindi pa
  
 2. Product Inquiry Page:
  > > > **Nakadefault na ang value (Temporary)** para sa verified account pag nagcomplete account ka, dahil **nakadisable muna sa utility or api yung otp sender at mail sender.** kaya once na nagcomplete account ka **no need for verification pwede mo ng gamitin ang mga features FOR NOW**

**Comment by johncarlostacruz** [comment]
01/25/24
- [ ] 6. Customer Information Collection:
>dimag continue may lumalabas na image
![image](https://github.com/MIS-SEG-Android-Team/Guanzon-Sales-Kit/assets/23698764/f7c4586f-4180-4cd9-89dc-5f016c719d9c)
